# Generated by Django 5.1.5 on 2025-02-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='note',
            name='password',
            field=models.TextField(default='this is hidden'),
        ),
    ]
