# Generated by Django 5.1.5 on 2025-02-05 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_note_metadata_alter_note_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='note',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='example.note'),
        ),
    ]
