# Generated by Django 5.1.5 on 2025-02-04 04:01

import jestit.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default=None, max_length=200)),
                ('kind', models.CharField(default=None, max_length=200)),
                ('description', models.TextField(default=None)),
            ],
            bases=(models.Model, jestit.models.base.JestitBase),
        ),
    ]
