# Generated by Django 5.1.5 on 2025-02-05 01:04

import jestit.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default=None, max_length=200)),
                ('kind', models.CharField(default=None, max_length=200)),
                ('description', models.TextField(default=None)),
                ('password', models.TextField(default=None)),
            ],
            bases=(models.Model, jestit.models.base.JestitBase),
        ),
    ]
